"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy": false
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    skip_untranslated_strings: false
    skip_untranslated_files: true
    export_only_approved: true
  - source: /fastlane/metadata/android/en-US/full_description.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
    skip_untranslated_strings: false
    skip_untranslated_files: true
    export_only_approved: true
  - source: /fastlane/metadata/android/en-US/short_description.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
    skip_untranslated_strings: false
    skip_untranslated_files: true
    export_only_approved: true
  - source: /fastlane/metadata/android/en-US/title.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
    skip_untranslated_strings: false
    skip_untranslated_files: true
    export_only_approved: true
