[versions]
agp = "9.4.0"
appcompat = "1.8.0"
checkstyle = "10.21.4"
preference = "1.2.1"
colorpicker = "1.1.0"
kotlin = "2.4.20"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
jaredrummler-colorpicker = { module = "com.jaredrummler:colorpicker", version.ref = "colorpicker" }
jetbrains-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }