---
name: crowdin

on:
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          config: .crowdin.yml
          create_pull_request: true
          push_translations: false
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PAT }}
