---
name: fastlane

on:
  workflow_dispatch:

permissions:
    actions: none
    attestations: none
    checks: none
    contents: read
    deployments: none
    id-token: none
    issues: none
    discussions: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: none

jobs:
  fastlane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
