---
name: fastlane

on:
  workflow_dispatch:

jobs:
  fastlane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
