---
name: fastlane

on:
  workflow_dispatch:

permissions:
    actions: none
    attestations: none
    checks: none
    contents: read
    deployments: none
    id-token: none
    issues: none
    discussions: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: none

jobs:
  fastlane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: main
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@c8857fdbbd3e00f9a5cbe8604bcecfa95ce8fef8 # v2.1.0
